# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
@EXPLICIT
https://conda.anaconda.org/pytorch/win-64/cuda90-1.0-0.tar.bz2
https://conda.anaconda.org/pytorch/win-64/cuda92-1.0-0.tar.bz2
https://conda.anaconda.org/menpo/win-64/ffmpeg-2.7.0-0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/_tflow_select-2.1.0-gpu.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/blas-1.0-mkl.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/ca-certificates-2019.3.9-hecc5488_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/cudatoolkit-10.0.130-0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/icc_rt-2019.0.0-h0cc432a_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/intel-openmp-2019.3-203.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/msys2-conda-epoch-20160418-1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pandoc-2.2.3.2-0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/vs2015_runtime-14.15.26706-h3a45250_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/winpty-0.4.3-4.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/cudnn-7.3.1-cuda10.0_0.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gmp-6.1.0-2.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-libwinpthread-git-5.0.0.4634.697f757-2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/mkl-2018.0.3-1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/vc-14.1-h0510ff6_4.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/icu-58.2-ha66f8fd_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/jpeg-9c-hfa6e2cd_1001.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libiconv-1.15-hfa6e2cd_1005.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/libsodium-1.0.16-h9d3ae62_0.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gcc-libs-core-5.3.0-7.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/openssl-1.1.1b-hfa6e2cd_2.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pcre-8.41-h6538335_1003.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pixman-0.34.0-hfa6e2cd_1003.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/python-3.7.0-hea74fb7_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/sqlite-3.27.2-he774522_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/tk-8.6.8-hfa6e2cd_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/xz-5.2.4-h2fa13f4_4.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/zlib-1.2.11-h2fa13f4_1004.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/astor-0.7.1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/atomicwrites-1.3.0-py37_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/attrs-19.1.0-py37_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/audioread-2.1.6-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/backcall-0.1.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/certifi-2019.3.9-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/colorama-0.4.1-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/decorator-4.4.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/defusedxml-0.5.0-py37_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/entrypoints-0.3-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/gast-0.2.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/hdf5-1.10.4-nompi_hcc15c50_1106.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/ipython_genutils-0.2.0-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/joblib-0.13.2-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/kiwisolver-1.0.1-py37h6538335_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libpng-1.6.36-h7602738_1000.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/libprotobuf-3.6.0-h1a1b453_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/llvmlite-0.28.0-py37ha925a31_0.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gcc-libgfortran-5.3.0-6.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/markdown-2.6.11-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/markupsafe-1.1.1-py37he774522_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/mistune-0.8.4-py37he774522_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/more-itertools-6.0.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/numpy-base-1.15.4-py37h8128ebf_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/olefile-0.46-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pandocfilters-1.4.2-py37_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/parso-0.3.4-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pickleshare-0.7.5-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pluggy-0.9.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/prometheus_client-0.6.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/py-1.8.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pycparser-2.19-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyparsing-2.3.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pyreadline-2.1-py37_1000.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pytz-2018.9-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/send2trash-1.5.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/simplegeneric-0.8.1-py37_2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/sip-4.19.8-py37h6538335_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/six-1.12.0-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/termcolor-1.1.0-py_2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/testpath-0.4.2-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/tornado-6.0.2-py37he774522_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/wcwidth-0.1.7-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/webencodings-0.5.1-py37_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/werkzeug-0.15.2-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/win_unicode_console-0.5-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/wincertstore-0.2-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/zeromq-4.2.5-he025d50_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/zstd-1.3.7-h508b16e_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/absl-py-0.7.1-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/cairo-1.16.0-hc1b38c8_1000.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/cffi-1.12.2-py37h7a1dbc1_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cycler-0.10.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/freetype-2.10.0-h5db478b_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/html5lib-1.0.1-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/jedi-0.13.3-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/libtiff-4.0.10-hb898794_2.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gcc-libs-5.3.0-7.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/protobuf-3.6.0-py37he025d50_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pyrsistent-0.14.11-py37he774522_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/python-dateutil-2.8.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pyzmq-17.1.2-py37hfa6e2cd_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/qt-5.9.7-vc14h73c81de_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/setuptools-40.8.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/traitlets-4.3.2-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/bleach-3.1.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/grpcio-1.16.1-py37h351948d_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/jinja2-2.10-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/jsonschema-3.0.1-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/jupyter_core-4.4.0-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libffi-3.2.1-h6538335_1006.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pillow-5.4.1-py37hdc69c19_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pycairo-1.18.0-py37h63da52a_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pygments-2.3.1-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pyqt-5.9.2-py37h6538335_2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pytest-4.3.1-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pywinpty-0.5.5-py37_1000.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/wheel-0.33.1-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/gettext-0.19.8.1-hb01d8f6_1002.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/jupyter_client-5.2.4-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/nbformat-4.4.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pip-19.0.3-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/prompt_toolkit-2.0.9-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/terminado-0.8.1-py37_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/glib-2.58.3-hc0c2ac7_1001.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/ipython-7.4.0-py37h39e3cac_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/nbconvert-5.4.1-py_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pbr-5.1.3-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/gobject-introspection-1.58.2-py37h1800f87_1000.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/ipykernel-5.1.0-py37h39e3cac_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/mock-2.0.0-py37_1001.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/jupyter_console-6.0.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/notebook-5.7.8-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pygobject-3.30.4-py37h5e4a255_1000.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/qtconsole-4.4.3-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/widgetsnbextension-3.4.2-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/ipywidgets-7.4.2-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/jupyter-1.0.0-py37_7.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/h5py-2.9.0-nompi_py37h3cb27cb_1102.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/keras-applications-1.0.7-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/matplotlib-3.0.3-py37hc8f65d3_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/mkl_fft-1.0.6-py37hdbbee80_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/mkl_random-1.0.1-py37h77b88f5_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/numpy-1.15.4-py37ha559c80_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/numba-0.43.1-py37hf9181ef_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pandas-0.24.2-py37ha925a31_0.tar.bz2
https://conda.anaconda.org/pytorch/win-64/pytorch-0.4.1-py37_cuda92_cudnn7he774522_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/scipy-1.1.0-py37h4f6bf74_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/tensorboard-1.13.1-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/tensorboardx-1.6-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/tensorflow-estimator-1.13.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/keras-preprocessing-1.0.9-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/resampy-0.2.1-py_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/scikit-learn-0.20.1-py37hb854c30_0.tar.bz2
https://conda.anaconda.org/pytorch/noarch/torchvision-0.2.1-py_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/librosa-0.6.3-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/tensorflow-base-1.13.1-gpu_py37h871c8ca_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/tensorflow-1.13.1-gpu_py37h83e5d6a_0.tar.bz2
